homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Frarik Database 1'
        author: 'Frarik'
        reference: 'github.com/Frarik/cards'
      setting:

####################################################
#                                                  #
#              IMPOSTAZIONI PACKAGE                #
#                                                  #
####################################################

        Sensore Database: &sensore_db "{{states('sensor.home_assistant_v2_db_dimensione')}}"
#        Sensore Database: &sensore_db "{{states('sensor.maria_db_esterno')}}"

        Device per notifica push: &push
          - service: IL_TUO_MOBILE_APP

####################################################
#                                                  #
#              NOTIFICHE GRUPPO                    #
#                                                  #
####################################################

notify:
  - name: Frarik Database
    platform: group
    services: *push

####################################################
#                                                  #
#                INPUT DATETIME                    #
#                                                  #
####################################################

input_datetime:
  frarik_db_orario_repack:
    name: Database Orario Repack
    has_date: false
    has_time: true
    icon: mdi:clock-outline

####################################################

  frarik_db_data_ultimo_repack:
    has_date: true
    has_time: false

####################################################
#                                                  #
#                INPUT NUMBER                      #
#                                                  #
####################################################

input_number:
  frarik_db_giorni_da_mantenere:
    name: Database Giorni da Mantenere
    min: 1
    max: 365
    unit_of_measurement: 'day'
    step: 1
    mode: box
    icon: mdi:calendar-today

####################################################

  frarik_db_dimensione_massima:
    name: Database Dimensione Massima
    min: 1
    max: 1000000
    unit_of_measurement: 'MB'
    step: 1
    mode: box
    icon: mdi:database-alert

####################################################
#                                                  #
#          INPUT NUMBER DIMENSIONE DB              #
#                                                  #
####################################################

  frarik_db_lunedi:
    name: Database Dimensione Lunedì
    icon: mdi:counter
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: MB

####################################################

  frarik_db_martedi:
    name: Database Dimensione Martedì
    icon: mdi:counter
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: MB

####################################################

  frarik_db_mercoledi:
    name: Database Dimensione Mercoledì
    icon: mdi:counter
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: MB

####################################################

  frarik_db_giovedi:
    name: Database Dimensione Giovedì
    icon: mdi:counter
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: MB

####################################################

  frarik_db_venerdi:
    name: Database Dimensione Venerdì
    icon: mdi:counter
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: MB

####################################################

  frarik_db_sabato:
    name: Database Dimensione Sabato
    icon: mdi:counter
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: MB

####################################################

  frarik_db_domenica:
    name: Database Dimensione Domenica
    icon: mdi:counter
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: MB

####################################################

  frarik_db_dimensione_precedente:
    name: Database Dimensione Precedente
    icon: mdi:counter
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: MB

####################################################
#                                                  #
#                    BOOLEAN                       #
#                                                  #
####################################################

input_boolean:
  frarik_db_repack_orario:
    name: Database Repack Automatico Orario

####################################################

  frarik_db_repack_dimensione:
    name: Database Repack per Dimensione

####################################################

  frarik_db_notifiche_push:
    name: Database Notifiche Push

####################################################
#                                                  #
#                BOOLEAN GIORNI                    #
#                                                  #
####################################################

  frarik_db_repack_lunedi:
    name: Database Repack Lunedì

#########################################################

  frarik_db_repack_martedi:
    name: Database Repack Martedì

#########################################################

  frarik_db_repack_mercoledi:
    name: Database Repack Mercoledì

#########################################################

  frarik_db_repack_giovedi:
    name: Database Repack Giovedì

#########################################################

  frarik_db_repack_venerdi:
    name: Database Repack Venerdì

#########################################################

  frarik_db_repack_sabato:
    name: Database Repack Sabato

#########################################################

  frarik_db_repack_domenica:
    name: Database Repack Domenica

####################################################
#                                                  #
#                    INPUT TEXT                    #
#                                                  #
####################################################

input_text:
  frarik_db_stato:

####################################################

  frarik_db_ultimo_repack:

####################################################

  frarik_db_data_reset:

####################################################
#                                                  #
#                     SENSORI                      #
#                                                  #
####################################################

sensor:
  - platform: min_max
    name: Frarik DB Media 7 Giorni
    type: median
    entity_ids:
      - input_number.frarik_db_lunedi
      - input_number.frarik_db_martedi
      - input_number.frarik_db_mercoledi
      - input_number.frarik_db_giovedi
      - input_number.frarik_db_venerdi
      - input_number.frarik_db_sabato
      - input_number.frarik_db_domenica

####################################################
#                                                  #
#                     TEMPLATE                     #
#                                                  #
####################################################

template:
  - sensor:
      - name: "Frarik Database Versione"
        unique_id: frarik_database_versione
        state: "1.0"
        icon: mdi:package-variant-closed

      - name: "Frarik DB Dimensione"
        unique_id: frarik_db_dimensione
        unit_of_measurement: MB
        icon: mdi:database
        state: *sensore_db

      - name: "Frarik DB Giorni Passati Repack"
        unique_id: frarik_db_giorni_passati_repack
        icon: mdi:counter
        state: >
          {% if states('input_datetime.frarik_db_data_ultimo_repack') not in ['unknown', 'unavailable'] %}
            {{ (as_timestamp(now()) - as_timestamp(states('input_datetime.frarik_db_data_ultimo_repack'))) | int(0) // 86400 }}
          {% else %}
            0
          {% endif %}

####################################################
#                                                  #
#                      SCRIPT                      #
#                                                  #
####################################################

script:
  frarik_db_repack:
    alias: Database Repack
    sequence:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ states('sensor.frarik_db_giorni_passati_repack') | int(0) >= states('input_number.frarik_db_giorni_da_mantenere') | int(0) }}"
            sequence:
              - service: notify.frarik_database
                data:
                  title: "⚙ Repack Database ⚙"
                  message: 'Repack DB Avviato il {{ now().strftime("%d/%m/%Y - %H:%M") }}'
              - service: input_number.set_value
                target:
                  entity_id: input_number.frarik_db_dimensione_precedente
                data:
                  value: "{{ states('sensor.frarik_db_dimensione') }}"
              - service: input_text.set_value
                target:
                  entity_id: input_text.frarik_db_stato
                data:
                  value: "In Corso"
              - service: recorder.purge
                data:
                  repack: true
                  keep_days: "{{ states('input_number.frarik_db_giorni_da_mantenere') | int(0) }}"
              - delay: "00:25:00"
              - service: input_text.set_value
                target:
                  entity_id: input_text.frarik_db_stato
                data:
                  value: "Standby"
              - service: input_text.set_value
                target:
                  entity_id: input_text.frarik_db_ultimo_repack
                data:
                  value: '{{ now().strftime("%d/%m/%Y - %H:%M") }}'
              - service: input_datetime.set_datetime
                target:
                  entity_id: input_datetime.frarik_db_data_ultimo_repack
                data:
                  date: '{{ now().strftime("%Y-%m-%d") }}'
              - condition: state
                entity_id: input_boolean.frarik_db_notifiche_push
                state: 'on'
              - service: notify.frarik_database
                data:
                  title: "✅ Repack DB Eseguito ✅"
                  message: >
                    Repack Eseguito il: {{ now().strftime("%d/%m/%Y - %H:%M") }}
                    DB Attuale: {{ states('sensor.frarik_db_dimensione') }} MB
                    DB Precedente: {{ states('input_number.frarik_db_dimensione_precedente') }} MB
                    DB Ridotto di: {{ (states('input_number.frarik_db_dimensione_precedente') | float(0) - states('sensor.frarik_db_dimensione') | float(0)) | round(2) }} MB
        default:
          - service: notify.frarik_database
            data:
              title: "⚠️ Repack DB non eseguito ⚠️"
              message: >
                Repack non eseguito. Sono passati solo {{ states('sensor.frarik_db_giorni_passati_repack') }} giorni dall'ultimo.
                Devono passare almeno {{ states('input_number.frarik_db_giorni_da_mantenere') }} giorni.

####################################################

  frarik_db_reset_sensori:
    sequence:
      - service: input_text.set_value
        data:
          value: >-
            {{now().strftime('%d/%m/%Y %H:%M')}}
        target:
          entity_id: input_text.frarik_db_data_reset
      - service: input_number.set_value
        data:
          value: '0'
        target:
          entity_id:
            - input_number.frarik_db_lunedi
            - input_number.frarik_db_martedi
            - input_number.frarik_db_mercoledi
            - input_number.frarik_db_giovedi
            - input_number.frarik_db_venerdi
            - input_number.frarik_db_sabato
            - input_number.frarik_db_domenica

####################################################
#                                                  #
#                   AUTOMAZIONI                    #
#                                                  #
####################################################

automation:
- alias: Frarik Database
  id: Frarik Database
  trigger:
  - platform: time
    at: 'input_datetime.frarik_db_orario_repack'
    id: repack_db_now
  - platform: template
    value_template: "{{ states('sensor.frarik_db_dimensione') | float(0) > states('input_number.frarik_db_dimensione_massima') | float(0) }}"
    id: repack_db_size_max
  - platform: time
    at: '23:59:00'
    id: incremento_db
  action:

####################################################
# Repack DB Automatico Fascia Oraria

  - choose:
    - conditions:
      - condition: trigger
        id: repack_db_now
      - condition: state
        entity_id: input_boolean.frarik_db_repack_orario
        state: 'on'
      - condition: template
        value_template: >-
          {% set today = now().strftime('%A') %}
          {% if (is_state("input_boolean.frarik_db_repack_lunedi", "on") and today == "Monday") %} true
          {% elif (is_state("input_boolean.frarik_db_repack_martedi", "on") and today == "Tuesday") %} true
          {% elif (is_state("input_boolean.frarik_db_repack_mercoledi", "on") and today == "Wednesday") %} true
          {% elif (is_state("input_boolean.frarik_db_repack_giovedi", "on") and today == "Thursday") %} true
          {% elif (is_state("input_boolean.frarik_db_repack_venerdi", "on") and today == "Friday") %} true
          {% elif (is_state("input_boolean.frarik_db_repack_sabato", "on") and today == "Saturday") %} true
          {% elif (is_state("input_boolean.frarik_db_repack_domenica", "on") and today == "Sunday") %} true
          {% else %} false
          {% endif %}
      sequence:
      - service: script.toggle
        entity_id: script.frarik_db_repack

####################################################
# Repack DB Automatico Dimensione Massima

  - choose:
    - conditions:
      - condition: trigger
        id: repack_db_size_max
      - condition: state
        entity_id: input_boolean.frarik_db_repack_dimensione
        state: 'on'
      sequence:
      - service: script.toggle
        entity_id: script.frarik_db_repack

####################################################
# Incremento DB giornaliero

  - choose:
    - conditions:
      - condition: trigger
        id: incremento_db
      sequence:
      - service: input_number.set_value
        target:
          entity_id: >
            input_number.frarik_db_{{ ['lunedi','martedi','mercoledi','giovedi','venerdi','sabato','domenica'][now().weekday()] }}
        data:
          value: "{{ states('sensor.frarik_db_dimensione') }}"
